checkpoint_mapping:
  name: local
  description: A description of this experiment

SAM_VIT_B: ["vit_b", "/checkpoints/sam_vit_b_01ec64.pth"]

SAM_VIT_L: ["vit_l", "/checkpoints/sam_vit_l_0b3195.pth"]

SAM_VIT_H: ["vit_h", "/checkpoints/sam_vit_h_4b8939.pth"]

SAM2_base_plus:
  ["model/sam2/sam2_hiera_b+.yaml", "checkpoints/sam2_hiera_base_plus.pt"]

SAM2_small: ["model/sam2/sam2_hiera_s.yaml", "checkpoints/sam2_hiera_small.pt"]

SAM2_tiny: ["model/sam2/sam2_hiera_t.yaml", "checkpoints/sam2_hiera_tiny.pt"]

SAM2.1_base_plus:
  ["model/sam2.1/sam2.1_hiera_b+.yaml", "checkpoints/sam2.1_hiera_base_plus.pt"]

SAM2.1_small:
  ["model/sam2.1/sam2.1_hiera_s.yaml", "checkpoints/sam2.1_hiera_small.pt"]

SAM2.1_tiny:
  ["model/sam2.1/sam2.1_hiera_t.yaml", "checkpoints/sam2.1_hiera_tiny.pt"]
